### ISSUE TITLE
Is there any instructions on installation

### ISSUE THREAD

**Issue by a4992214** [HansAcker/EDDN-RealTime#3]
Hi - I want to try this out - what are the instructions to install it locally?

**Comment by HansAcker** [comment]
Hi.
I'll try and add some instructions to the readme file.

Due to the way the Javascript loads, the HTML page must be served through HTTP(S). I updated the files to use relative paths, so you can check out the repository, copy the html directory to a webserver and just use my websocket service for the data.

To run the websocket server, I use Python virtualenv and pip to install the required libraries. It even works in WSL on Windows.
```
git clone https://github.com/HansAcker/EDDN-RealTime
cd EDDN-RealTime/eddnws
virtualenv venv
. venv/bin/activate
pip install -r requirements.txt 
python3 ./eddnws.py -v
```
You could then change the ``socketUrl`` in js/board.js to something like ``ws://127.0.0.1:8081`` and use your own service.

**Comment by HansAcker** [comment]
Updated the README file with instructions.
